<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CREATE_BUTTON</name>
   <tag></tag>
   <elementGuidId>5d44257a-a5ce-42ce-9b4c-5c8877aeb546</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button//Span[text()='Create']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
