<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Allocate</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>1339a1ed-b0ab-43ad-b2f0-40bf0ca9d9cb</testSuiteGuid>
   <testCaseLink>
      <guid>5fc470e1-9f41-4729-b9e6-e958be5e9af8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Allocate/VPAC83/TC001_Allocate_VPAC83_ValidateTheReservationOfFirearmToTheUser</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>529f8f35-9532-4fad-9865-a1495cf15ee6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>367a8bde-d6cc-46a1-b4e6-e93d89c830b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2408148e-402a-49e9-bcd2-34a877b09249</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5030eaa3-e2bf-4d5c-9e94-b51f7794c32c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecfb647b-0cb2-4fc8-8e27-9adf58f7ddab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4cb4f6d-27e3-4fbc-8862-4366d1eba9bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1908d92c-848d-4ffa-a8e7-28ac4f6ef249</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83b448ea-6392-4e06-ab2d-6ab36ccd90f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97c8ba15-07dd-4a73-a1d2-6c079639ff4d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
