<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Audit</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>45c4cce9-02b3-4c26-b3ce-164387fd1a06</testSuiteGuid>
   <testCaseLink>
      <guid>65d71df9-1451-4369-89fb-eb549bbabaa8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Audit/VPAC66/TC001_Audit_VPAC66_CreateAuditJob</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bcda75b-9cca-4f3f-8291-8d6225ab8aea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83b4cd82-ac69-41b2-be26-f3bcd706cbfa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c6f66d0-0fa6-453f-8819-a3c1920c9703</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f17b3099-a7af-40ae-99b7-ab2e309b1512</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1d2541b6-3517-44e1-9d4c-07c04e083ecb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Audit/VPAC66/TC002_Audit_VPAC66_AddAuditJobParticipant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>256fa587-36c8-421b-8f2b-177331c08b59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fb86a10-d5ee-4207-a3af-4133baa16cf3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2cbabc5-ad08-424f-b10c-dc8c8944dee8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e75bb4e-3103-4d59-8775-7db2453cd020</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04c413ff-d7bc-43c4-9750-8f92c38bb75d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab42e0a3-9244-4492-8535-70036650b0b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a16149ed-deeb-4ea2-a33b-ee80964090bd</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
