<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Manage_Equipment_Item</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>9c3d1ac8-91d9-49bb-9852-b50f32f9d64c</testSuiteGuid>
   <testCaseLink>
      <guid>6e227afb-2b55-4f19-b3b8-65ceb24471ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Manage_Equipment_Item/VPAC25/TC003_Manage Equipment item_VPAC25_ValidateCreatingAn OCSprayWithoutPopulatingOptionalFields</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3afdf34-b3ac-4dad-9e6d-05865209f7e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41a9e40a-a9d8-4d01-b76f-0ebb5b525f74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60167524-6a34-4cd2-8f0b-fe1777e5f943</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8172b74d-f4e7-4206-a1f1-0d5db77c8e34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77385e4a-2745-403a-86a9-03a7cb9e402b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d588cfda-2daa-4db5-bb2e-ac9d9952a48c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73a65d0e-12aa-4175-bf66-2c4ffdd37c55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fef5e97-1d74-402e-9182-18ffb4cd9f1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e20b0841-64a5-4553-9eb3-36bde0261d84</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
