<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ADD_BUTTON</name>
   <tag></tag>
   <elementGuidId>adc3afed-9bf4-4740-bd85-83e9c5229d17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-id=&quot;add&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
