<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SAVE_BUTTON</name>
   <tag></tag>
   <elementGuidId>f4e900c1-8698-45b0-9e99-c158c6ff3adf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-id='saveAndClose']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>[data-id='saveAndClose']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
