<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SAVE_BUTTON</name>
   <tag></tag>
   <elementGuidId>00030550-73ea-4c95-83e8-f7f01e7ba6f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-id='saveAndContinue']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>[data-id='saveAndClose']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
