<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VALIDATE_ID</name>
   <tag></tag>
   <elementGuidId>fdcc4dbd-ed90-483d-ba61-cdca9129510c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.hc-title-data-key</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
