<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CREATE_NOTES_CHECKBOX</name>
   <tag></tag>
   <elementGuidId>5715f209-f60a-4650-a713-27dcef1178f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.hc-checkbox-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
